# Generated by Django 5.1.5 on 2025-02-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_image.jpg', upload_to='profile_images'),
        ),
    ]
