# Generated by Django 5.1.5 on 2025-02-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='events_assets'),
        ),
    ]
